---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: alfresco-process-services-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: alfresco-process-services
  chart:
    git: git@github.com:camorra-skk/helm-operator-get-started
    path: charts/alfresco-process-services
    ref: master
  values:
    image:
      repository: camorraskk/acs-store-selector
      tag: dev-zbfjkcod
    replicaCount: 1
    hpa:
      enabled: false
