---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: alfresco-process-services-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: dev
  chart:
    git: git@github.com:camorra-skk/helm-operator-get-started
    path: charts/alfresco-process-services
    ref: master
    skipDepUpdate: true
  values:
    processEngine:
      image:
        repository: camorraskk/acs-store-selector
        tag: dev-jjhptjhf

