---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: dev
  chart:
    git: git@github.com:camorra-skk/helm-operator-get-started
    path: charts/nginx-chart
    ref: master
    skipDepUpdate: true
  values:
    processEngine:
      image:
        repository: camorraskk/podinfo
        tag: dev-aosuvtl1

